version: "3.7"
services:
  app:
    container_name: va-cedar-frontend
    build:
      context: .
      dockerfile: Dockerfile
      target: builder
    volumes:
      - ".:/app"
      - "/app/node_modules"
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
    tty: true
    command: npm start
